<?php
$GLOBALS['filetypedata'] = array('av' => array('av', 'wmv', 'wav' , 'mov' , 'avi' , 'mpeg' ),
			'real' => array('rm', 'rmvb'),
			'binary' => array('dat'),
			'flash' => array('swf'),
			'html' => array('html', 'htm'),
			'image' => array('gif', 'jpg', 'jpeg', 'png', 'bmp'),
			'office' => array('doc', 'xls', 'ppt' , 'docx'),
			'pdf' => array('pdf'),
			'rar' => array('rar'),
			'text' => array('txt'),
			'bt' => array('bt'),
			'zip' => array('tar', 'rar', 'zip', 'gz'));
$GLOBALS['mime_types'] = array( 
		'gif' => 'image/gif', 
		'jpg' => 'image/jpeg', 
		'jpeg' => 'image/jpeg', 
		'jpe' => 'image/jpeg', 
		'bmp' => 'image/bmp', 
		'png' => 'image/png', 
		'tif' => 'image/tiff', 
		'tiff' => 'image/tiff', 
		'pict' => 'image/x-pict', 
		'pic' => 'image/x-pict', 
		'pct' => 'image/x-pict', 
		'tif' => 'image/tiff', 
		'tiff' => 'image/tiff', 
		'psd' => 'image/x-photoshop', 
		
		'swf' => 'application/x-shockwave-flash', 
		'js' => 'application/x-javascript', 
		'pdf' => 'application/pdf', 
		'ps' => 'application/postscript', 
		'eps' => 'application/postscript', 
		'ai' => 'application/postscript', 
		'wmf' => 'application/x-msmetafile', 
		
		'css' => 'text/css', 
		'htm' => 'text/html', 
		'html' => 'text/html', 
		'txt' => 'text/plain', 
		'xml' => 'text/xml', 
		'wml' => 'text/wml', 
		'wbmp' => 'image/vnd.wap.wbmp', 
		
		'mid' => 'audio/midi', 
		'wav' => 'audio/wav', 
		'mp3' => 'audio/mpeg', 
		'mp2' => 'audio/mpeg', 
		
		'avi' => 'video/x-msvideo', 
		'mpeg' => 'video/mpeg', 
		'mpg' => 'video/mpeg', 
		'qt' => 'video/quicktime', 
		'mov' => 'video/quicktime', 
		
		'lha' => 'application/x-lha', 
		'lzh' => 'application/x-lha', 
		'z' => 'application/x-compress', 
		'gtar' => 'application/x-gtar', 
		'gz' => 'application/x-gzip', 
		'gzip' => 'application/x-gzip', 
		'tgz' => 'application/x-gzip', 
		'tar' => 'application/x-tar', 
		'bz2' => 'application/bzip2', 
		'zip' => 'application/zip', 
		'arj' => 'application/x-arj', 
		'rar' => 'application/x-rar-compressed', 
		
		'hqx' => 'application/mac-binhex40', 
		'sit' => 'application/x-stuffit', 
		'bin' => 'application/x-macbinary', 
		
		'uu' => 'text/x-uuencode', 
		'uue' => 'text/x-uuencode', 
		
		'latex'=> 'application/x-latex', 
		'ltx' => 'application/x-latex', 
		'tcl' => 'application/x-tcl', 
		
		'pgp' => 'application/pgp', 
		'asc' => 'application/pgp', 
		'exe' => 'application/x-msdownload', 
		'doc' => 'application/msword', 
		'rtf' => 'application/rtf', 
		'xls' => 'application/vnd.ms-excel', 
		'ppt' => 'application/vnd.ms-powerpoint', 
		'mdb' => 'application/x-msaccess', 
		'wri' => 'application/x-mswrite', 
);